/**
 * The repository's formatting, stated so a formatter conforms to it instead of
 * overriding it (MUSE-58).
 *
 * Until this file existed there was no `.prettierrc`, no `.editorconfig`, no `biome.json`,
 * no eslint config and no `format` script. The convention was single quotes — 6,713 string
 * literals, unanimous — but it was written down nowhere, and **Prettier's default is
 * `singleQuote: false`**. So `npx prettier --write <file>` did not follow the repository;
 * it rewrote the file against it. MUSE-45's agent reached for exactly that command and the
 * pull request arrived as 538 insertions / 319 deletions for a 96-line change, 348 of the
 * added lines pure requoting, with all five CI checks green. The 96 lines that mattered
 * were unreviewable until the change was redone.
 *
 * Every value below was **measured** against the tree rather than chosen, by formatting a
 * scratch copy under each candidate and counting the resulting diff. The tree agrees with
 * Prettier's defaults on everything except quotes:
 *
 *   semi: true              flipping it rewrites 78 files / 8,411 lines
 *   tabWidth: 2             flipping it rewrites 76 files / 19,589 lines
 *   useTabs: false          flipping it rewrites 76 files / 19,737 lines
 *   trailingComma: 'all'    'none' rewrites 72 files, 'es5' 64
 *   arrowParens: 'always'   'avoid' rewrites 60 files
 *   bracketSpacing: true    flipping it rewrites 73 files
 *   quoteProps: 'as-needed' 'consistent' costs 47 extra lines
 *   objectWrap: 'preserve'  'collapse' costs 6 files
 *
 * They are therefore *not* restated here: a config that repeats a default is a config that
 * has to be re-measured when the default moves. Only the two settings that differ from the
 * default are written down, and both are load-bearing.
 *
 * ## `printWidth` is a fit, not a fact — and this is the one honest caveat
 *
 * **The tree is not Prettier-formatted and no `printWidth` makes it so.** At the best value
 * Prettier still rewraps 43 of 78 TypeScript and `.mjs` files; 35 files are clean at no
 * tested width at all, because they were wrapped by hand. Clean-file counts across the
 * sweep: 80 → 15/78, 88 → 27, 92 → 33, **96 → 35**, 100 → 31, 120 → 17.
 *
 * 96 is the maximum, so it is the value that reflows the fewest files when one is next
 * touched. It is not a claim that the repository wraps at 96 — it demonstrably disagrees
 * with itself — and it is why **`prettier --check` is not the gate here**. Making it the
 * gate would require reformatting the whole tree, which is the defect this ticket exists to
 * prevent: a diff nobody can review that invalidates every open branch at once. What is
 * enforced instead is the invariant the tree actually holds, in `scripts/check-format.mjs`.
 * Files conform the rest of the way as they are touched.
 *
 * ## The override is not cosmetic: `sanity typegen` reads this file
 *
 * `@sanity/codegen` formats its generated output by calling Prettier's `resolveConfig()` on
 * the output path and then `format()` with whatever comes back (see
 * `node_modules/@sanity/codegen/dist/utils/resolveFormatter.js`). `resolveConfig` does not
 * consult `.prettierignore` — that is a CLI concern — so an ignore entry would not protect
 * the file. `src/lib/sanity/sanity.types.ts` is committed as Prettier *defaults* (double
 * quotes, width 80) because that is what the generator emitted with no config present.
 *
 * Without the override below, the next `npm run sanity:types` would re-emit all 146 lines of
 * it in single quotes at width 96. That does not merely churn: `ci.yml`'s `sanity` job
 * regenerates the artefacts and diffs them, so the job would go red on a branch that never
 * touched the schema, blaming the schema. Pinning the one generated file to the style it is
 * generated in keeps the generator and the repository agreeing. `scripts/check-format.mjs`
 * asserts that by running a full `prettier --check` on exactly that file, so if a future
 * `@sanity/codegen` changes its formatting the check says so rather than CI guessing.
 *
 * ## What this file deliberately does not own
 *
 * See `.prettierignore`. In short: no Astro parser is installed, prose wrapping is a human
 * decision, and `src/styles/tokens.css` is a hand-aligned table of uppercase hex that
 * Prettier flattens and lowercases.
 */
export default {
  /**
   * The whole of MUSE-45's damage, in one line. Note that Prettier's rule is
   * escape-minimising rather than absolute: a literal containing an apostrophe and no
   * double quote is still written with double quotes, which is what the 168 double-quoted
   * literals in the tree already are.
   */
  singleQuote: true,

  /** Measured: the value that leaves the most of the tree alone. See above. */
  printWidth: 96,

  overrides: [
    {
      // Generated by `sanity typegen`, which resolves this config. See above.
      files: 'src/lib/sanity/sanity.types.ts',
      options: { singleQuote: false, printWidth: 80 },
    },
  ],
};
