/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  studioName: string;
  tagline: LocaleString;
  summary: LocaleText;
  address: string;
  email: string;
  phone?: string;
  openingHours?: LocaleText;
  social?: Array<{
    platform: "instagram" | "facebook" | "linktree" | "tiktok" | "youtube";
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
};

export type LocaleString = {
  _type: "localeString";
  hr: string;
  en: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LocaleText = {
  _type: "localeText";
  hr: string;
  en: string;
};

export type ProsePage = {
  _id: string;
  _type: "prosePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  route:
    | "/"
    | "/whatisbachata"
    | "/schedule"
    | "/pricing"
    | "/aboutus"
    | "/contact"
    | "/privacy";
  heading: LocaleString;
  lede: LocaleText;
  sections: Array<{
    heading: LocaleString;
    body: Array<
      {
        _key: string;
      } & LocaleText
    >;
    _type: "prosePageSection";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  route:
    | "/"
    | "/whatisbachata"
    | "/schedule"
    | "/pricing"
    | "/aboutus"
    | "/contact"
    | "/privacy";
  name: LocaleString;
  title: LocaleString;
  description: LocaleString;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: LocaleString;
  answer: LocaleText;
  order?: number;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocaleString;
  slug: Slug;
  publishedAt: string;
  excerpt: LocaleText;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
  body: LocaleRichText;
  author?: InstructorReference;
};

export type LocaleRichText = {
  _type: "localeRichText";
  hr: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type GalleryImage = {
  _id: string;
  _type: "galleryImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
  caption?: LocaleString;
  takenAt?: string;
  order?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocaleString;
  slug: Slug;
  eventType: "party" | "workshop" | "bootcamp" | "social";
  startsAt: string;
  endsAt?: string;
  venue: string;
  description: LocaleText;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
  lineup?: Array<string>;
  ticketUrl?: string;
};

export type PricingTier = {
  _id: string;
  _type: "pricingTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: LocaleString;
  priceEur: number;
  period: "class" | "course" | "month" | "package";
  features: Array<
    {
      _key: string;
    } & LocaleString
  >;
  featured: boolean;
  order?: number;
};

export type ClassReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "class";
};

export type ScheduleSlot = {
  _id: string;
  _type: "scheduleSlot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  class: ClassReference;
  day: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
  start: string;
  instructors?: Array<
    {
      _key: string;
    } & InstructorReference
  >;
  active: boolean;
};

export type Class = {
  _id: string;
  _type: "class";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: LocaleString;
  slug: Slug;
  level: "beginner" | "improver" | "intermediate" | "advanced";
  description?: LocaleText;
  durationMin: number;
  instructors: Array<
    {
      _key: string;
    } & InstructorReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
  order?: number;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: LocaleString;
  bio?: LocaleText;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: LocaleString;
    _type: "image";
  };
  instagram?: string;
  order?: number;
};

export type StudioStory = {
  _id: string;
  _type: "studioStory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: LocaleString;
  foundedOn?: string;
  story: Array<
    {
      _key: string;
    } & LocaleText
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | LocaleString
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleText
  | ProsePage
  | Page
  | Faq
  | InstructorReference
  | Post
  | LocaleRichText
  | Slug
  | GalleryImage
  | Event
  | PricingTier
  | ClassReference
  | ScheduleSlot
  | Class
  | Instructor
  | StudioStory
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    _id,    studioName,    tagline{ hr, en },    summary{ hr, en },    address,    email,    phone,    openingHours{ hr, en },    social[]{ platform, url },    shareImage{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  studioName: string;
  tagline: {
    hr: string;
    en: string;
  };
  summary: {
    hr: string;
    en: string;
  };
  address: string;
  email: string;
  phone: string | null;
  openingHours: {
    hr: string;
    en: string;
  } | null;
  social: Array<{
    platform: "facebook" | "instagram" | "linktree" | "tiktok" | "youtube";
    url: string;
  }> | null;
  shareImage: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page"] | order(route asc){    _id,    route,    name{ hr, en },    title{ hr, en },    description{ hr, en }  }
export type PAGES_QUERY_RESULT = Array<{
  _id: string;
  route:
    | "/"
    | "/aboutus"
    | "/contact"
    | "/pricing"
    | "/privacy"
    | "/schedule"
    | "/whatisbachata";
  name: {
    hr: string;
    en: string;
  };
  title: {
    hr: string;
    en: string;
  };
  description: {
    hr: string;
    en: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: PROSE_PAGES_QUERY
// Query: *[_type == "prosePage"] | order(route asc){    _id,    route,    heading{ hr, en },    lede{ hr, en },    "sections": sections[]{      heading{ hr, en },      "body": body[]{ hr, en }    }  }
export type PROSE_PAGES_QUERY_RESULT = Array<{
  _id: string;
  route:
    | "/"
    | "/aboutus"
    | "/contact"
    | "/pricing"
    | "/privacy"
    | "/schedule"
    | "/whatisbachata";
  heading: {
    hr: string;
    en: string;
  };
  lede: {
    hr: string;
    en: string;
  };
  sections: Array<{
    heading: {
      hr: string;
      en: string;
    };
    body: Array<{
      hr: string;
      en: string;
    }>;
  }>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: SCHEDULE_QUERY
// Query: *[_type == "scheduleSlot" && active == true] | order(start asc){    _id,    day,    start,    "classId": class->_id,    "classRef": class._ref,    "name": class->name{ hr, en },    "level": class->level,    "durationMin": class->durationMin,    "instructors": coalesce(instructors[]->name, class->instructors[]->name),    "instructorRefs": coalesce(instructors[]._ref, class->instructors[]._ref)  }
export type SCHEDULE_QUERY_RESULT = Array<{
  _id: string;
  day: "fri" | "mon" | "sat" | "sun" | "thu" | "tue" | "wed";
  start: string;
  classId: string;
  classRef: string;
  name: {
    hr: string;
    en: string;
  };
  level: "advanced" | "beginner" | "improver" | "intermediate";
  durationMin: number;
  instructors: Array<string>;
  instructorRefs: Array<string>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: CLASSES_QUERY
// Query: *[_type == "class"] | order(coalesce(order, 999) asc, name.hr asc){    _id,    "slug": slug.current,    name{ hr, en },    level,    description{ hr, en },    durationMin,    "instructors": instructors[]->name,    "instructorRefs": instructors[]._ref,    image{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop }  }
export type CLASSES_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  name: {
    hr: string;
    en: string;
  };
  level: "advanced" | "beginner" | "improver" | "intermediate";
  description: {
    hr: string;
    en: string;
  } | null;
  durationMin: number;
  instructors: Array<string>;
  instructorRefs: Array<string>;
  image: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(coalesce(order, 999) asc, name asc){    _id,    name,    "slug": slug.current,    role{ hr, en },    bio{ hr, en },    portrait{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop },    instagram  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  role: {
    hr: string;
    en: string;
  };
  bio: {
    hr: string;
    en: string;
  } | null;
  portrait: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  instagram: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: STUDIO_STORY_QUERY
// Query: *[_type == "studioStory" && _id == "studioStory"][0]{    _id,    heading{ hr, en },    foundedOn,    "story": story[]{ hr, en }  }
export type STUDIO_STORY_QUERY_RESULT = {
  _id: "studioStory";
  heading: {
    hr: string;
    en: string;
  };
  foundedOn: string | null;
  story: Array<{
    hr: string;
    en: string;
  }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: PRICING_QUERY
// Query: *[_type == "pricingTier"] | order(coalesce(order, 999) asc, priceEur asc){    _id,    name{ hr, en },    priceEur,    period,    "features": features[]{ hr, en },    featured  }
export type PRICING_QUERY_RESULT = Array<{
  _id: string;
  name: {
    hr: string;
    en: string;
  };
  priceEur: number;
  period: "class" | "course" | "month" | "package";
  features: Array<{
    hr: string;
    en: string;
  }>;
  featured: boolean;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && (!defined(endsAt) && startsAt >= $now || endsAt >= $now)] | order(startsAt asc){    _id,    "slug": slug.current,    title{ hr, en },    eventType,    startsAt,    endsAt,    venue,    description{ hr, en },    lineup,    ticketUrl,    image{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop }  }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  title: {
    hr: string;
    en: string;
  };
  eventType: "bootcamp" | "party" | "social" | "workshop";
  startsAt: string;
  endsAt: string | null;
  venue: string;
  description: {
    hr: string;
    en: string;
  };
  lineup: Array<string> | null;
  ticketUrl: string | null;
  image: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_type == "galleryImage"] | order(coalesce(order, 999) asc, takenAt desc){    _id,    caption{ hr, en },    takenAt,    image{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop }  }
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  caption: {
    hr: string;
    en: string;
  } | null;
  takenAt: string | null;
  image: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && publishedAt <= $now] | order(publishedAt desc){    _id,    "slug": slug.current,    title{ hr, en },    publishedAt,    excerpt{ hr, en },    "author": author->name,    "authorRef": author._ref,    coverImage{ "assetId": asset._ref, alt{ hr, en }, hotspot, crop },    body{ hr, en }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  title: {
    hr: string;
    en: string;
  };
  publishedAt: string;
  excerpt: {
    hr: string;
    en: string;
  };
  author: string | null;
  authorRef: string | null;
  coverImage: {
    assetId: string | null;
    alt: {
      hr: string;
      en: string;
    };
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  body: {
    hr: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h3" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    en: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h3" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(coalesce(order, 999) asc, question.hr asc){    _id,    question{ hr, en },    answer{ hr, en }  }
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  question: {
    hr: string;
    en: string;
  };
  answer: {
    hr: string;
    en: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: DOCUMENT_COUNTS_QUERY
// Query: {    "siteSettings": count(*[_type == "siteSettings"]),    "studioStory": count(*[_type == "studioStory"]),    "page": count(*[_type == "page"]),    "prosePage": count(*[_type == "prosePage"]),    "class": count(*[_type == "class"]),    "scheduleSlot": count(*[_type == "scheduleSlot"]),    "instructor": count(*[_type == "instructor"]),    "pricingTier": count(*[_type == "pricingTier"]),    "event": count(*[_type == "event"]),    "galleryImage": count(*[_type == "galleryImage"]),    "post": count(*[_type == "post"]),    "faq": count(*[_type == "faq"])  }
export type DOCUMENT_COUNTS_QUERY_RESULT = {
  siteSettings: number;
  studioStory: number;
  page: number;
  prosePage: number;
  class: number;
  scheduleSlot: number;
  instructor: number;
  pricingTier: number;
  event: number;
  galleryImage: number;
  post: number;
  faq: number;
};
