import type { Locale } from '../i18n';
import type { ClassEntry, Level, Style, Weekday } from '../schedule';
import type { PageMetaDoc, ScheduleEntry } from './decode';
import type {
  CLASSES_QUERY_RESULT,
  FAQS_QUERY_RESULT,
  INSTRUCTORS_QUERY_RESULT,
  PAGES_QUERY_RESULT,
  PRICING_QUERY_RESULT,
  SCHEDULE_QUERY_RESULT,
  SITE_SETTINGS_QUERY_RESULT,
} from './sanity.types';

/**
 * Where the schema and the site are tied together **at compile time**.
 *
 * `src/lib/sanity/sanity.types.ts` is generated by `sanity typegen` from the real
 * schema and the real queries. That makes it the one artefact that knows whether a GROQ
 * projection still matches the schema — and the assertions below turn that knowledge
 * into `astro check` failures.
 *
 * The mechanism is worth stating plainly, because it is the answer to "a field rename
 * can't silently break a page". GROQ does not error on an attribute that does not
 * exist; it returns `null`. So when a schema field is renamed and the types are
 * regenerated, the projection's type for that field becomes exactly `null`. Every
 * `Guaranteed<…>` line here therefore stops compiling, naming the query and the field.
 *
 * Two layers sit either side of this one, because this layer only fires once the types
 * have been regenerated:
 *
 *   - `scripts/check-sanity.mjs`, run by `npm run build`, fails if any schema source
 *     file has changed since `sanity/schema.json` and these types were generated. That
 *     closes the window where a rename exists in TypeScript but not in the artefacts.
 *   - `test/sanity.test.ts` asserts the same field names against the extracted schema
 *     JSON, so `npm test` catches it too, with a message aimed at a human.
 *
 * Nothing here emits code; the whole module is types. It is imported by
 * `test/sanity.test.ts` purely so `astro check` and `tsc` are guaranteed to see it.
 */

/**
 * Compiles only if `T[K]` cannot be `null`.
 *
 * `[null] extends [T[K]]` is the distribution-proof form: `null extends string | null`
 * is true for the union *and* for a bare `null`, which is precisely the two cases that
 * mean "the schema no longer guarantees this field" — it went optional, or it stopped
 * existing. The error message is carried in the type itself so the compiler prints
 * something useful rather than `Type 'false' is not assignable to type 'true'`.
 */
type Guaranteed<T, K extends keyof T> = [null] extends [T[K]]
  ? {
      ERROR: 'This field is no longer guaranteed by the Sanity schema. Either it was renamed (GROQ returns null for an attribute that does not exist) or its validation stopped being required(). Fix the schema or the query in src/lib/sanity/queries.ts — do not relax this assertion.';
      field: K;
    }
  : true;

/** Compiles only if `A` and `B` are the same type, in both directions. */
type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : { ERROR: 'B is wider'; A: A; B: B }) : { ERROR: 'A is wider'; A: A; B: B };

/* ------------------------------------------------------------------------- */
/* The enums are structure, and the generated types prove the loop is closed. */
/* ------------------------------------------------------------------------- */

/**
 * `LEVELS`, `STYLES` and `WEEKDAYS` live in `src/lib/schedule.ts`; the Studio builds its
 * option lists from those same constants (`sanity/schemaTypes/enums.ts`), so the schema
 * cannot offer a value the renderer does not know — and `sanity typegen` reads the
 * option list back out of the extracted schema as a string union.
 *
 * These three lines close that circle. Add a fourth level in `schedule.ts` without
 * regenerating and `scripts/check-sanity.mjs` fails; regenerate and these still hold;
 * type a fourth level *anywhere else* and one of them stops compiling. It is the MUSE-11
 * guarantee — one source for a level name — extended across the CMS boundary.
 */
type SlotRow = SCHEDULE_QUERY_RESULT[number];

export type AssertScheduleLevels = Same<SlotRow['level'], Level>;
export type AssertScheduleStyles = Same<SlotRow['style'], Style>;
export type AssertScheduleDays = Same<SlotRow['day'], Weekday>;

const _levels: AssertScheduleLevels = true;
const _styles: AssertScheduleStyles = true;
const _days: AssertScheduleDays = true;

/**
 * A decoded schedule row still *is* a `ClassEntry`.
 *
 * This is the compile-time half of the promise in `src/data/schedule.ts`'s header: that
 * replacing the placeholder rows is a prop change and nothing else. `Schedule.astro`
 * takes `ClassEntry[]`; if the CMS read path ever stops producing one, the error lands
 * here rather than in the grid.
 */
export type AssertScheduleEntryIsClassEntry = ScheduleEntry extends ClassEntry ? true : never;
const _entry: AssertScheduleEntryIsClassEntry = true;

/* ------------------------------------------------------------------------- */
/* Required fields, per query. One line per field a page cannot render without. */
/* ------------------------------------------------------------------------- */

const _slotFields: [
  Guaranteed<SlotRow, '_id'>,
  Guaranteed<SlotRow, 'day'>,
  Guaranteed<SlotRow, 'start'>,
  Guaranteed<SlotRow, 'classId'>,
  Guaranteed<SlotRow, 'name'>,
  Guaranteed<SlotRow, 'style'>,
  Guaranteed<SlotRow, 'level'>,
  Guaranteed<SlotRow, 'durationMin'>,
  Guaranteed<SlotRow, 'instructor'>,
] = [true, true, true, true, true, true, true, true, true];

type ClassRow = CLASSES_QUERY_RESULT[number];
const _classFields: [
  Guaranteed<ClassRow, '_id'>,
  Guaranteed<ClassRow, 'slug'>,
  Guaranteed<ClassRow, 'name'>,
  Guaranteed<ClassRow, 'style'>,
  Guaranteed<ClassRow, 'level'>,
  Guaranteed<ClassRow, 'description'>,
  Guaranteed<ClassRow, 'durationMin'>,
  Guaranteed<ClassRow, 'instructor'>,
  Guaranteed<ClassRow, 'image'>,
] = [true, true, true, true, true, true, true, true, true];

type InstructorRow = INSTRUCTORS_QUERY_RESULT[number];
const _instructorFields: [
  Guaranteed<InstructorRow, '_id'>,
  Guaranteed<InstructorRow, 'name'>,
  Guaranteed<InstructorRow, 'slug'>,
  Guaranteed<InstructorRow, 'role'>,
  Guaranteed<InstructorRow, 'bio'>,
  Guaranteed<InstructorRow, 'portrait'>,
] = [true, true, true, true, true, true];

type TierRow = PRICING_QUERY_RESULT[number];
const _tierFields: [
  Guaranteed<TierRow, '_id'>,
  Guaranteed<TierRow, 'name'>,
  Guaranteed<TierRow, 'priceEur'>,
  Guaranteed<TierRow, 'period'>,
  Guaranteed<TierRow, 'featured'>,
] = [true, true, true, true, true];

type FaqRow = FAQS_QUERY_RESULT[number];
const _faqFields: [
  Guaranteed<FaqRow, '_id'>,
  Guaranteed<FaqRow, 'question'>,
  Guaranteed<FaqRow, 'answer'>,
] = [true, true, true];

type PageRow = PAGES_QUERY_RESULT[number];
const _pageFields: [
  Guaranteed<PageRow, '_id'>,
  Guaranteed<PageRow, 'route'>,
  Guaranteed<PageRow, 'name'>,
  Guaranteed<PageRow, 'title'>,
  Guaranteed<PageRow, 'description'>,
] = [true, true, true, true, true];

/**
 * The singleton is nullable by construction — `[0]` on an empty set is `null` — so the
 * assertion is on the document's fields, not on the document.
 *
 * `phone` and `openingHours` are deliberately **not** here (MUSE-20). They were, and the
 * two lines had to come out when both fields became optional — which is the assertion
 * working rather than being relaxed: `Guaranteed` stops compiling the moment a field can
 * be `null`, so an optional field cannot be left on this list by accident. The decision
 * to make them optional is recorded on `SiteSettings` in `./decode.ts`: the site renders
 * neither, no real value exists for either, and a required field with no consumer can
 * only be filled in with fiction.
 */
type SettingsRow = NonNullable<SITE_SETTINGS_QUERY_RESULT>;
const _settingsFields: [
  Guaranteed<SettingsRow, 'studioName'>,
  Guaranteed<SettingsRow, 'tagline'>,
  Guaranteed<SettingsRow, 'summary'>,
  Guaranteed<SettingsRow, 'address'>,
  Guaranteed<SettingsRow, 'email'>,
] = [true, true, true, true, true];

/* ------------------------------------------------------------------------- */
/* Bilingual values arrive as Record<Locale, string>, which is what the site  */
/* already speaks. This is the two-fields localisation decision, type-checked. */
/* ------------------------------------------------------------------------- */

export type AssertLocalisedIsRecord = FaqRow['question'] extends Record<Locale, string>
  ? true
  : never;
const _localised: AssertLocalisedIsRecord = true;

/**
 * A decoded `page` carries exactly the fields a page and `llms.txt` render from it.
 * Spelled out rather than compared to a type in `src/lib/pages.ts`, which after MUSE-20
 * holds the route list and no copy at all.
 */
export type AssertPageMetaShape = PageMetaDoc extends {
  route: string;
  name: Record<Locale, string>;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
}
  ? true
  : never;
const _pageMeta: AssertPageMetaShape = true;

/**
 * Nothing above is used at runtime; the `const`s exist only to make the compiler
 * evaluate the types. Exported as one frozen object so no linter prunes them and
 * `test/sanity.test.ts` can import the module to guarantee it is type-checked.
 */
export const SCHEMA_ASSERTIONS = Object.freeze({
  levels: _levels,
  styles: _styles,
  days: _days,
  scheduleEntryIsClassEntry: _entry,
  localisedIsRecord: _localised,
  pageMetaShape: _pageMeta,
  fields: Object.freeze({
    scheduleSlot: _slotFields,
    class: _classFields,
    instructor: _instructorFields,
    pricingTier: _tierFields,
    faq: _faqFields,
    page: _pageFields,
    siteSettings: _settingsFields,
  }),
});
