import type { Locale } from '../i18n';
import type { ClassEntry, Level, Weekday } from '../schedule';
import type { PageMetaDoc, ScheduleEntry } from './decode';
import type {
  CLASSES_QUERY_RESULT,
  FAQS_QUERY_RESULT,
  INSTRUCTORS_QUERY_RESULT,
  PAGES_QUERY_RESULT,
  PRICING_QUERY_RESULT,
  SCHEDULE_QUERY_RESULT,
  SITE_SETTINGS_QUERY_RESULT,
  STUDIO_STORY_QUERY_RESULT,
} from './sanity.types';

/**
 * Where the schema and the site are tied together **at compile time**.
 *
 * `src/lib/sanity/sanity.types.ts` is generated by `sanity typegen` from the real
 * schema and the real queries. That makes it the one artefact that knows whether a GROQ
 * projection still matches the schema — and the assertions below turn that knowledge
 * into `astro check` failures.
 *
 * The mechanism is worth stating plainly, because it is the answer to "a field rename
 * can't silently break a page". GROQ does not error on an attribute that does not
 * exist; it returns `null`. So when a schema field is renamed and the types are
 * regenerated, the projection's type for that field becomes exactly `null`. Every
 * `Guaranteed<…>` line here therefore stops compiling, naming the query and the field.
 *
 * Two layers sit either side of this one, because this layer only fires once the types
 * have been regenerated:
 *
 *   - `scripts/check-sanity.mjs`, run by `npm run build`, fails if any schema source
 *     file has changed since `sanity/schema.json` and these types were generated. That
 *     closes the window where a rename exists in TypeScript but not in the artefacts.
 *   - `test/sanity.test.ts` asserts the same field names against the extracted schema
 *     JSON, so `npm test` catches it too, with a message aimed at a human.
 *
 * Nothing here emits code; the whole module is types. It is imported by
 * `test/sanity.test.ts` purely so `astro check` and `tsc` are guaranteed to see it.
 */

/**
 * Compiles only if `T[K]` cannot be `null`.
 *
 * `[null] extends [T[K]]` is the distribution-proof form: `null extends string | null`
 * is true for the union *and* for a bare `null`, which is precisely the two cases that
 * mean "the schema no longer guarantees this field" — it went optional, or it stopped
 * existing. The error message is carried in the type itself so the compiler prints
 * something useful rather than `Type 'false' is not assignable to type 'true'`.
 */
type Guaranteed<T, K extends keyof T> = [null] extends [T[K]]
  ? {
      ERROR: 'This field is no longer guaranteed by the Sanity schema. Either it was renamed (GROQ returns null for an attribute that does not exist) or its validation stopped being required(). Fix the schema or the query in src/lib/sanity/queries.ts — do not relax this assertion.';
      field: K;
    }
  : true;

/** Compiles only if `A` and `B` are the same type, in both directions. */
type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : { ERROR: 'B is wider'; A: A; B: B }) : { ERROR: 'A is wider'; A: A; B: B };

/* ------------------------------------------------------------------------- */
/* The enums are structure, and the generated types prove the loop is closed. */
/* ------------------------------------------------------------------------- */

/**
 * `LEVELS` and `WEEKDAYS` live in `src/lib/schedule.ts`; the Studio builds its option
 * lists from those same constants (`sanity/schemaTypes/enums.ts`), so the schema cannot
 * offer a value the renderer does not know — and `sanity typegen` reads the option list
 * back out of the extracted schema as a string union.
 *
 * These two lines close that circle, and MUSE-36 is the first time the loop has actually
 * been exercised: adding `improver` in `schedule.ts` without regenerating fails
 * `scripts/check-sanity.mjs`; regenerating makes these hold again with four levels; typing
 * a fifth level *anywhere else* stops one of them compiling. It is the MUSE-11 guarantee —
 * one source for a level name — extended across the CMS boundary.
 *
 * `AssertScheduleStyles` used to be the third. It is gone with `class.style` and `STYLES`
 * (MUSE-36), and its absence is covered from the other side: `scripts/check-sanity.mjs`'s
 * read contract no longer lists the field, and `test/sanity.test.ts` asserts the schema
 * has no `style` on `class` at all — so the field cannot come back without a decision.
 */
type SlotRow = SCHEDULE_QUERY_RESULT[number];

export type AssertScheduleLevels = Same<SlotRow['level'], Level>;
export type AssertScheduleDays = Same<SlotRow['day'], Weekday>;

const _levels: AssertScheduleLevels = true;
const _days: AssertScheduleDays = true;

/**
 * Two teachers on one class arrive as a list of names, not a name (MUSE-36).
 *
 * `Same<…, string[]>` rather than `Guaranteed`, because the failure this is aimed at is a
 * *shape* change and not an absence: revert `instructors` to a single reference and the
 * projection still resolves, to `string`, which every template that renders a joined
 * phrase would accept by printing the first teacher's name and nothing else.
 */
export type AssertScheduleInstructorsAreAList = Same<SlotRow['instructors'], string[]>;
const _instructors: AssertScheduleInstructorsAreAList = true;

/**
 * A decoded schedule row still *is* a `ClassEntry`.
 *
 * `src/data/schedule.ts` promised in its header that replacing the placeholder rows would
 * be a prop change and nothing else, and this was the compile-time half of that promise.
 * MUSE-36 collected on it: the file is gone, `Schedule.astro` and `Home.astro` take
 * `ClassEntry[]`, and if the CMS read path ever stops producing one the error lands here
 * rather than in the grid.
 */
export type AssertScheduleEntryIsClassEntry = ScheduleEntry extends ClassEntry ? true : never;
const _entry: AssertScheduleEntryIsClassEntry = true;

/* ------------------------------------------------------------------------- */
/* Required fields, per query. One line per field a page cannot render without. */
/* ------------------------------------------------------------------------- */

const _slotFields: [
  Guaranteed<SlotRow, '_id'>,
  Guaranteed<SlotRow, 'day'>,
  Guaranteed<SlotRow, 'start'>,
  Guaranteed<SlotRow, 'classId'>,
  Guaranteed<SlotRow, 'name'>,
  Guaranteed<SlotRow, 'level'>,
  Guaranteed<SlotRow, 'durationMin'>,
  Guaranteed<SlotRow, 'instructors'>,
] = [true, true, true, true, true, true, true, true];

type ClassRow = CLASSES_QUERY_RESULT[number];
const _classFields: [
  Guaranteed<ClassRow, '_id'>,
  Guaranteed<ClassRow, 'slug'>,
  Guaranteed<ClassRow, 'name'>,
  Guaranteed<ClassRow, 'level'>,
  Guaranteed<ClassRow, 'durationMin'>,
  Guaranteed<ClassRow, 'instructors'>,
] = [true, true, true, true, true, true];

/**
 * `description` and `image` are optional (MUSE-36), and still projected.
 *
 * They were on the `Guaranteed` list and had to come off when the fields stopped being
 * `required()` — the assertion working rather than being relaxed. The homepage style
 * cards were the only consumer of either and they went with `class.style`, so a required
 * field would have been one nothing renders and nobody has a real value for, which is the
 * shape of fiction. `OptionalIn` keeps both honest from the other side: a deleted
 * projection, a renamed one, and a `required()` quietly returning all fail here.
 */
export type AssertClassDescriptionOptional = OptionalIn<ClassRow, 'description'>;
export type AssertClassImageOptional = OptionalIn<ClassRow, 'image'>;

const _classDescriptionOptional: AssertClassDescriptionOptional = true;
const _classImageOptional: AssertClassImageOptional = true;

/**
 * `bio`, `portrait` and `instagram` are deliberately **not** on this list (MUSE-23 for the
 * last two, MUSE-36 for the first), the same way `phone` and `openingHours` came off the
 * `siteSettings` list in MUSE-20 — and for the same reason, which is this assertion working
 * rather than being relaxed.
 *
 * `Guaranteed` stops compiling the moment a field can be `null`, so the two lines *had* to
 * come out when both fields became optional; an optional field cannot be left here by
 * accident. The decision itself is recorded on `Instructor` in `./decode.ts`: no
 * photography of this studio exists, and an instructor may have no public Instagram, so a
 * required field for either could only be satisfied with fiction (MUSE-36).
 *
 * What still holds the two of them honest is `AssertInstructorPortraitOptional` below —
 * a field that goes back to being required also breaks a build, from the other side.
 */
type InstructorRow = INSTRUCTORS_QUERY_RESULT[number];
const _instructorFields: [
  Guaranteed<InstructorRow, '_id'>,
  Guaranteed<InstructorRow, 'name'>,
  Guaranteed<InstructorRow, 'slug'>,
  Guaranteed<InstructorRow, 'role'>,
] = [true, true, true, true];

/**
 * The three optional instructor fields are *still projected*, and still optional.
 *
 * Dropping a field off `Guaranteed` leaves nothing watching it: delete `instagram` from
 * the query and `INSTRUCTORS_QUERY_RESULT` simply stops having the key, which no
 * `Guaranteed` line can notice because there is no line. These say the key is there
 * **and** that it can be absent — so a deleted projection, a renamed one, and a
 * `required()` quietly returning all fail here, naming the field.
 */
type OptionalIn<T, K extends keyof T> = [null] extends [T[K]]
  ? true
  : {
      ERROR: 'This field is projected as non-nullable, which means the Sanity schema now requires it. It is optional on purpose: no photography of this studio exists (MUSE-23), an instructor may have no public Instagram (MUSE-23), nobody has written a bio for a real instructor (MUSE-36), and no class has copy or a photograph now that the invented style cards are gone (MUSE-36). A required field with no value can only be filled in with fiction, which is how the invented schedule reached production. If the real content now exists, say so in the schema AND move this to the Guaranteed list above — do not delete the assertion.';
      field: K;
    };

export type AssertInstructorBioOptional = OptionalIn<InstructorRow, 'bio'>;
export type AssertInstructorPortraitOptional = OptionalIn<InstructorRow, 'portrait'>;
export type AssertInstructorInstagramOptional = OptionalIn<InstructorRow, 'instagram'>;

const _bioOptional: AssertInstructorBioOptional = true;
const _portraitOptional: AssertInstructorPortraitOptional = true;
const _instagramOptional: AssertInstructorInstagramOptional = true;

/**
 * The origin story's fields, all three of which `/aboutus` cannot render without.
 *
 * The singleton is nullable by construction — `[0]` on an empty set is `null` — so, as
 * with `siteSettings`, the assertion is on the document's fields rather than on the
 * document. `story` being an array is asserted separately: `Guaranteed` would be satisfied
 * by a renamed projection that happened to resolve to a single object.
 */
type StoryRow = NonNullable<STUDIO_STORY_QUERY_RESULT>;
const _storyFields: [
  Guaranteed<StoryRow, 'heading'>,
  Guaranteed<StoryRow, 'foundedOn'>,
  Guaranteed<StoryRow, 'story'>,
] = [true, true, true];

export type AssertStoryIsParagraphs = Same<
  StoryRow['story'],
  Record<Locale, string>[]
>;
const _storyParagraphs: AssertStoryIsParagraphs = true;

type TierRow = PRICING_QUERY_RESULT[number];
const _tierFields: [
  Guaranteed<TierRow, '_id'>,
  Guaranteed<TierRow, 'name'>,
  Guaranteed<TierRow, 'priceEur'>,
  Guaranteed<TierRow, 'period'>,
  Guaranteed<TierRow, 'featured'>,
] = [true, true, true, true, true];

type FaqRow = FAQS_QUERY_RESULT[number];
const _faqFields: [
  Guaranteed<FaqRow, '_id'>,
  Guaranteed<FaqRow, 'question'>,
  Guaranteed<FaqRow, 'answer'>,
] = [true, true, true];

type PageRow = PAGES_QUERY_RESULT[number];
const _pageFields: [
  Guaranteed<PageRow, '_id'>,
  Guaranteed<PageRow, 'route'>,
  Guaranteed<PageRow, 'name'>,
  Guaranteed<PageRow, 'title'>,
  Guaranteed<PageRow, 'description'>,
] = [true, true, true, true, true];

/**
 * The singleton is nullable by construction — `[0]` on an empty set is `null` — so the
 * assertion is on the document's fields, not on the document.
 *
 * `phone` and `openingHours` are deliberately **not** here (MUSE-20). They were, and the
 * two lines had to come out when both fields became optional — which is the assertion
 * working rather than being relaxed: `Guaranteed` stops compiling the moment a field can
 * be `null`, so an optional field cannot be left on this list by accident. The decision
 * to make them optional is recorded on `SiteSettings` in `./decode.ts`: the site renders
 * neither, no real value exists for either, and a required field with no consumer can
 * only be filled in with fiction.
 */
type SettingsRow = NonNullable<SITE_SETTINGS_QUERY_RESULT>;
const _settingsFields: [
  Guaranteed<SettingsRow, 'studioName'>,
  Guaranteed<SettingsRow, 'tagline'>,
  Guaranteed<SettingsRow, 'summary'>,
  Guaranteed<SettingsRow, 'address'>,
  Guaranteed<SettingsRow, 'email'>,
] = [true, true, true, true, true];

/* ------------------------------------------------------------------------- */
/* Bilingual values arrive as Record<Locale, string>, which is what the site  */
/* already speaks. This is the two-fields localisation decision, type-checked. */
/* ------------------------------------------------------------------------- */

export type AssertLocalisedIsRecord = FaqRow['question'] extends Record<Locale, string>
  ? true
  : never;
const _localised: AssertLocalisedIsRecord = true;

/**
 * A decoded `page` carries exactly the fields a page and `llms.txt` render from it.
 * Spelled out rather than compared to a type in `src/lib/pages.ts`, which after MUSE-20
 * holds the route list and no copy at all.
 */
export type AssertPageMetaShape = PageMetaDoc extends {
  route: string;
  name: Record<Locale, string>;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
}
  ? true
  : never;
const _pageMeta: AssertPageMetaShape = true;

/**
 * Nothing above is used at runtime; the `const`s exist only to make the compiler
 * evaluate the types. Exported as one frozen object so no linter prunes them and
 * `test/sanity.test.ts` can import the module to guarantee it is type-checked.
 */
export const SCHEMA_ASSERTIONS = Object.freeze({
  levels: _levels,
  days: _days,
  scheduleInstructorsAreAList: _instructors,
  scheduleEntryIsClassEntry: _entry,
  localisedIsRecord: _localised,
  pageMetaShape: _pageMeta,
  classDescriptionOptional: _classDescriptionOptional,
  classImageOptional: _classImageOptional,
  bioOptional: _bioOptional,
  portraitOptional: _portraitOptional,
  instagramOptional: _instagramOptional,
  storyParagraphs: _storyParagraphs,
  fields: Object.freeze({
    scheduleSlot: _slotFields,
    class: _classFields,
    instructor: _instructorFields,
    pricingTier: _tierFields,
    faq: _faqFields,
    page: _pageFields,
    siteSettings: _settingsFields,
    studioStory: _storyFields,
  }),
});
