/**
 * Record the fingerprint of the schema sources, right after the artefacts are generated.
 *
 * Run as the last step of `npm run sanity:types`, so `sanity/schema.stamp.json` always
 * describes the sources that `sanity/schema.json` and `src/lib/sanity/sanity.types.ts`
 * were built from. `scripts/check-sanity.mjs` compares against it on every build.
 *
 * The stamp is committed. That is the point: a pull request that edits a schema file
 * without regenerating shows up as a diff whose `schema.stamp.json` was not touched, and
 * the build fails before review has to notice.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { fingerprint, STAMP_JSON } from './check-sanity.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const stamp = {
  _comment:
    'Generated by `npm run sanity:types`. Hashes of every file the Sanity schema is ' +
    'built from; `scripts/check-sanity.mjs` fails the build if one has moved since. ' +
    'Do not edit by hand — regenerate.',
  sources: fingerprint(),
};

writeFileSync(`${ROOT}${STAMP_JSON}`, `${JSON.stringify(stamp, null, 2)}\n`);
console.log(`Stamped ${Object.keys(stamp.sources).length} schema source file(s).`);
